"""Catálogo normalizado desde `Stock de Equipos San Luis V.1.xlsx`.

Solo se incluyen existencias sin una marca explícita de venta, alquiler o
asignación. Las personas y números de serie no se exponen en el catálogo web.
"""


def item(
    sku,
    name,
    brand,
    category,
    quantity,
    *,
    part_number="",
    used=False,
    sheet,
    balances=None,
    specs=None,
    description="",
):
    condition = "usado" if used else "nuevo"
    return {
        "sku": sku,
        "name": name,
        "brand": brand,
        "category": category,
        "part_number": part_number,
        "quantity": quantity,
        "is_used": used,
        "source_sheet": sheet,
        "balances": balances or [{"warehouse": "san-luis", "quantity": quantity}],
        "short_description": f"{name}. Stock real disponible: {quantity} unidad{'es' if quantity != 1 else ''}.",
        "description": description or (
            f"Producto registrado en el inventario físico de Alfil. "
            f"Condición: {condition}. Disponibilidad sujeta a confirmación comercial."
        ),
        "specs": {"Condición": condition.capitalize(), **(specs or {})},
        "highlights": ["Stock registrado en inventario", "Cotización con asesor de Alfil"],
    }


INVENTORY_PRODUCTS = [
    item("3E3T0LS-USED", "HP ProDesk 600 G6 Mini i5 16GB 256GB SSD", "hp", "computadoras", 1,
         part_number="3E3T0LS#ABM", used=True, sheet="USADOS",
         specs={"Procesador": "Intel Core i5", "Memoria": "16 GB", "Almacenamiento": "256 GB SSD"}),
    item("6Q0G1LS-USED", "HP Z2 G8 SFF Workstation i7", "hp", "computadoras", 1,
         part_number="6Q0G1LS", used=True, sheet="USADOS",
         specs={"Procesador": "Intel Core i7", "Memoria": "16 GB", "Almacenamiento": "512 GB M.2"}),
    item("6V9T9LS-USED", "HP ProDesk 400 G7 SFF i5 16GB", "hp", "computadoras", 1,
         part_number="6V9T9LS", used=True, sheet="USADOS",
         specs={"Procesador": "Intel Core i5", "Memoria": "16 GB", "Almacenamiento": "250 GB M.2"}),

    item("HP-P24-G4", "Monitor HP P24 G4 23.8 pulgadas", "hp", "componentes", 139,
         part_number="1A7E5AA#ABA", sheet="Monitor P24 G4 23.8",
         balances=[{"warehouse": "san-luis", "quantity": 137, "supplier": "ingram", "reference": "GR 018-0047450/0047451"},
                   {"warehouse": "san-borja", "quantity": 2, "supplier": "hdst", "reference": "GR 187"}],
         specs={"Pantalla": "23.8 pulgadas", "Modelo": "P24 G4"}),
    item("HP-P27H-G5", "Monitor HP P27h G5 FHD", "hp", "componentes", 40,
         part_number="64W41AA", sheet="HP P27h G5", specs={"Pantalla": "27 pulgadas", "Resolución": "Full HD"}),

    item("HUAWEI-MATEPAD-11-5", "Huawei MatePad 11.5 8GB 256GB", "huawei", "computadoras", 20,
         part_number="TXZ-W09", sheet="Tablet Huawei", specs={"Memoria": "8 GB", "Almacenamiento": "256 GB", "Color": "Gris"}),
    item("HUAWEI-KA11-KB11", "Huawei Smart Keyboard para MatePad 11.5", "huawei", "componentes", 20,
         part_number="KA11-KB11", sheet="Tablet Huawei", specs={"Color": "Negro", "Compatibilidad": "Huawei MatePad 11.5"}),

    item("HP-ZB16G10-I7", "HP ZBook Firefly 16 G10 i7", "hp", "laptops", 2,
         part_number="860Y3LA#ABM", sheet="Laptop ZB16G10 i7",
         balances=[{"warehouse": "san-borja", "quantity": 2, "supplier": "nexsys", "reference": "GR 37686"}],
         specs={"Procesador": "Intel Core i7", "Memoria": "16 GB DDR5-5200", "Almacenamiento": "1 TB SSD", "Gráficos": "NVIDIA RTX A500 4 GB", "Sistema": "Windows 11 Pro"}),
    item("HP-Z4-G4T", "HP Z4 G4T Workstation Xeon W2295", "hp", "computadoras", 13,
         part_number="877Z9LS#ABM-FF-C1", sheet="WT Z4G4T",
         specs={"Procesador": "Intel Xeon W-2295", "Memoria": "32 GB", "Almacenamiento": "1 TB"}),
    item("HP-Z2-G8-SFF", "HP Z2 G8 SFF Workstation i7", "hp", "computadoras", 8,
         part_number="6C5J4LS#ABM-FF-C1", sheet="Z2 DeskTop i7",
         balances=[{"warehouse": "san-luis", "quantity": 7, "supplier": "ingram", "reference": "GR 00005566"},
                   {"warehouse": "san-borja", "quantity": 1, "supplier": "ingram", "reference": "GR 00005566"}],
         specs={"Procesador": "Intel Core i7-11700", "Memoria": "16 GB", "Almacenamiento": "512 GB M.2"}),
    item("HP-Z2-TOWER-G9", "HP Z2 Tower G9 Workstation i7", "hp", "computadoras", 2,
         part_number="823G8LA#ABM", sheet="Z2 Tower G9 WT",
         specs={"Procesador": "Intel Core i7", "Memoria": "32 GB", "Almacenamiento": "2 TB", "Gráficos": "12 GB", "Sistema": "Windows 11 Pro"}),
    item("HP-400-G7-SFF", "HP ProDesk 400 G7 SFF i5 32GB 1TB", "hp", "computadoras", 6,
         part_number="6V9T9LS#ABM", sheet="CPU400G7",
         specs={"Procesador": "Intel Core i5", "Memoria": "32 GB", "Almacenamiento": "1 TB"}),
    item("HP-MINI-260-G4", "HP Desktop Mini 260 G4 i3", "hp", "computadoras", 7,
         part_number="246F4LT#ABM", sheet="MINI260 G4",
         specs={"Procesador": "Intel Core i3", "Memoria": "4 GB", "Almacenamiento": "1 TB"}),
    item("HP-MINI-400-G9", "HP Pro Mini 400 G9 i5", "hp", "computadoras", 4,
         part_number="A00NGLS#ABM", sheet="MINI400 G9",
         specs={"Procesador": "Intel Core i5", "Memoria": "16 GB", "Almacenamiento": "512 GB", "Sistema": "Windows 11 Pro"}),

    item("CISCO-C2960X-USED", "Switch Cisco Catalyst WS-C2960X-48FPD-L", "cisco", "redes-y-conectividad", 3,
         part_number="C2960X", used=True, sheet="Switch UPS Transceivers usados",
         balances=[{"warehouse": "san-borja", "quantity": 3}], specs={"Puertos": "48", "Observación": "Equipos usados; una unidad sin orejas"}),
    item("SALICRU-SLC-2000-TWIN", "UPS Salicru SLC-2000-TWIN PRO2 IEC", "salicru", "componentes", 3,
         part_number="699CA000017", used=True, sheet="Switch UPS Transceivers usados"),
    item("CISCO-GLC-SX-MMD-USED", "Transceiver Cisco GLC-SX-MMD", "cisco", "redes-y-conectividad", 1,
         part_number="10-2626-01", used=True, sheet="Switch UPS Transceivers usados"),
    item("CISCO-GLC-SX-MM", "Transceiver Cisco GLC-SX-MM", "cisco", "redes-y-conectividad", 5,
         part_number="30-1301-02", sheet="Switch UPS Transceivers usados"),
    item("CISCO-SFP-10G-SR", "Transceiver Cisco SFP-10G-SR", "cisco", "redes-y-conectividad", 38,
         part_number="10-2415-03", sheet="Switch UPS Transceivers usados"),
    item("CISCO-GLC-T", "Transceiver Cisco GLC-T", "cisco", "redes-y-conectividad", 6,
         sheet="Switch UPS Transceivers usados"),
    item("CISCO-GLC-LH-SM", "Transceiver Cisco GLC-LH-SM", "cisco", "redes-y-conectividad", 4,
         sheet="Switch UPS Transceivers usados"),
    item("HUAWEI-SFP-GE-SX-MM850", "Transceiver Huawei SFP-GE-SX-MM850", "huawei", "redes-y-conectividad", 1,
         part_number="02315204", sheet="Switch UPS Transceivers usados"),
    item("HP-X130-10G-SR", "Transceiver HP X130 10G SFP+ LC SR", "hp", "redes-y-conectividad", 1,
         part_number="AFBR-703SDZ-HP8", sheet="Switch UPS Transceivers usados"),
    item("AVAGO-AFBR-57F5MZ", "Transceiver Avago AFBR-57F5MZ-ELX", "avago", "redes-y-conectividad", 4,
         sheet="Switch UPS Transceivers usados"),
    item("BROCADE-32G-SW-SEC", "Transceiver Brocade 32G SW-SEC", "brocade", "redes-y-conectividad", 1,
         part_number="57-1000485-01", sheet="Switch UPS Transceivers usados"),
    item("LENOVO-1000BASE-T", "Transceiver Lenovo 1000BASE-T", "lenovo", "redes-y-conectividad", 4,
         part_number="78P3824", sheet="Switch UPS Transceivers usados"),
    item("HUAWEI-10G-02310MNW", "Transceiver Huawei SFP-10G-USR", "huawei", "redes-y-conectividad", 6,
         part_number="02310MNW", sheet="Switch UPS Transceivers usados"),

    # Inventario físico de San Borja incorporado desde `INVENTARIO - SB.xlsx`.
    item("HP-P224", "Monitor HP P224 21.5 pulgadas", "hp", "componentes", 23,
         part_number="L47536-001", sheet="INVENTARIO - SB.xlsx / PRIMER PISO",
         balances=[{"warehouse": "san-borja", "quantity": 23}],
         specs={"Modelo": "HP P224", "Pantalla": "21.5 pulgadas", "Resolución": "Full HD"}),
    item("HP-P204V", "Monitor HP P204v 19.5 pulgadas", "hp", "componentes", 10,
         part_number="L47850-B11", sheet="INVENTARIO - SB.xlsx / PRIMER PISO",
         balances=[{"warehouse": "san-borja", "quantity": 10}],
         specs={"Modelo": "HP P204v", "Pantalla": "19.5 pulgadas", "Resolución": "HD+"}),
    item("HP-P22V-G4", "Monitor HP P22v G4 21.5 pulgadas", "hp", "componentes", 1,
         part_number="L96110-004", sheet="INVENTARIO - SB.xlsx / PRIMER PISO",
         balances=[{"warehouse": "san-borja", "quantity": 1}],
         specs={"Modelo": "HP P22v G4", "Pantalla": "21.5 pulgadas", "Resolución": "Full HD"}),
    item("HP-PROONE-400-G4-AIO", "HP ProOne 400 G4 All-in-One 23.8 pulgadas", "hp", "computadoras", 6,
         part_number="5DV82LA#ABM", sheet="INVENTARIO - SB.xlsx / PRIMER PISO",
         balances=[{"warehouse": "san-borja", "quantity": 6}],
         specs={"Familia": "HP ProOne 400 G4", "Formato": "All-in-One", "Pantalla": "23.8 pulgadas"}),
    item("HP-PROONE-440-G9-AIO", "HP ProOne 440 G9 All-in-One 23.8 pulgadas", "hp", "computadoras", 1,
         part_number="787M0LA#ABM", sheet="INVENTARIO - SB.xlsx / PRIMER PISO",
         balances=[{"warehouse": "san-borja", "quantity": 1}],
         specs={"Familia": "HP ProOne 440 G9", "Formato": "All-in-One", "Pantalla": "23.8 pulgadas"}),
    item("HP-250-G8", "Laptop HP 250 G8 15.6 pulgadas", "hp", "laptops", 129,
         sheet="INVENTARIO - SB.xlsx / SEGUNDO PISO",
         balances=[{"warehouse": "san-borja", "quantity": 129}],
         specs={"Familia": "HP 250 G8", "Pantalla": "15.6 pulgadas"}),
    item("HP-240-G9", "Laptop HP 240 G9 14 pulgadas", "hp", "laptops", 2,
         sheet="INVENTARIO - SB.xlsx / SEGUNDO PISO",
         balances=[{"warehouse": "san-borja", "quantity": 2}],
         specs={"Familia": "HP 240 G9", "Pantalla": "14 pulgadas"}),
    item("HP-240-G10", "Laptop HP 240 G10 14 pulgadas", "hp", "laptops", 2,
         sheet="INVENTARIO - SB.xlsx / SEGUNDO PISO",
         balances=[{"warehouse": "san-borja", "quantity": 2}],
         specs={"Familia": "HP 240 G10", "Pantalla": "14 pulgadas"}),

    item("HP-W9085MC", "Tóner HP W9085MC", "hp", "toners-y-suministros", 1333,
         part_number="W9085MC", sheet="TONERS",
         balances=[{"warehouse": "san-borja", "quantity": 1284}, {"warehouse": "callao", "quantity": 49}]),
    item("HP-W9085-STARTER", "Tóner HP W9085 de inicio", "hp", "toners-y-suministros", 5,
         part_number="W9085", sheet="TONERS",
         balances=[{"warehouse": "callao", "quantity": 5}]),
    item("HP-W9065MC", "Tóner HP W9065MC", "hp", "toners-y-suministros", 624,
         part_number="W9065MC", sheet="TONERS",
         balances=[{"warehouse": "san-borja", "quantity": 618}, {"warehouse": "callao", "quantity": 6}]),
    item("HP-W1950X", "Tóner HP W1950X", "hp", "toners-y-suministros", 138,
         part_number="W1950X", sheet="TONERS",
         balances=[{"warehouse": "san-borja", "quantity": 138}]),
    item("HP-145X", "Tóner HP 145X", "hp", "toners-y-suministros", 70,
         part_number="W1450X", sheet="TONERS",
         balances=[{"warehouse": "callao", "quantity": 70}]),
    item("HP-145X-STARTER", "Tóner HP 145X de inicio", "hp", "toners-y-suministros", 18,
         part_number="145X-STARTER", sheet="TONERS",
         balances=[{"warehouse": "callao", "quantity": 18}]),
    item("CANON-GPR-63", "Tóner Canon GPR-63", "canon", "toners-y-suministros", 195,
         part_number="GPR-63", sheet="TONERS",
         balances=[{"warehouse": "san-borja", "quantity": 20}, {"warehouse": "callao", "quantity": 175}]),
]
